--- tag
insert into tag values(seq_tag_id.nextval, '태그1');
insert into tag values(seq_tag_id.nextval, '태그2');
insert into tag values(seq_tag_id.nextval, '태그3');
insert into tag values(seq_tag_id.nextval, '태그4');
insert into tag values(seq_tag_id.nextval, '태그5');
insert into tag values(seq_tag_id.nextval, '태그6');
insert into tag values(seq_tag_id.nextval, '태그7');
insert into tag values(seq_tag_id.nextval, '태그8');
insert into tag values(seq_tag_id.nextval, '태그9');

--- region
insert into region values (seq_region_id.nextval, '서울시', '강남구' );
insert into region values (seq_region_id.nextval, '서울시', '강동구' );
insert into region values (seq_region_id.nextval, '서울시', '강북구' );
insert into region values (seq_region_id.nextval, '서울시', '강서구' );
insert into region values (seq_region_id.nextval, '서울시', '관악구' );
insert into region values (seq_region_id.nextval, '서울시', '구로구' );
insert into region values (seq_region_id.nextval, '서울시', '금천구' );
insert into region values (seq_region_id.nextval, '서울시', '서초구' );
insert into region values (seq_region_id.nextval, '서울시', '동작구' );
insert into region values (seq_region_id.nextval, '서울시', '영등포구' );
insert into region values (seq_region_id.nextval, '인천', '중구' );
insert into region values (seq_region_id.nextval, '인천', '부평구' );
insert into region values (seq_region_id.nextval, '인천', '계양구' );
insert into region values (seq_region_id.nextval, '인천', '서구' );
insert into region values (seq_region_id.nextval, '인천', '남동구' );
insert into region values (seq_region_id.nextval, '인천', '연수구' );
insert into region values (seq_region_id.nextval, '인천', '동구' );
insert into region values (seq_region_id.nextval, '인천', '강화군' );
insert into region values (seq_region_id.nextval, '인천', '옹진군' );
insert into region values (seq_region_id.nextval, '경기도', '수원시' );
insert into region values (seq_region_id.nextval, '경기도', '성남시' );
insert into region values (seq_region_id.nextval, '경기도', '의정부시' );
insert into region values (seq_region_id.nextval, '경기도', '안양시' );
insert into region values (seq_region_id.nextval, '경기도', '부천시' );
insert into region values (seq_region_id.nextval, '경기도', '광명시' );
insert into region values (seq_region_id.nextval, '경기도', '평택시' );
insert into region values (seq_region_id.nextval, '경기도', '안산시' );
insert into region values (seq_region_id.nextval, '경기도', '고양시' );
insert into region values (seq_region_id.nextval, '경기도', '과천시' );
insert into region values (seq_region_id.nextval, '강원도', '춘천시' );
insert into region values (seq_region_id.nextval, '강원도', '원주시' );
insert into region values (seq_region_id.nextval, '강원도', '강릉시' );
insert into region values (seq_region_id.nextval, '강원도', '동해시' );
insert into region values (seq_region_id.nextval, '강원도', '속초시' );
insert into region values (seq_region_id.nextval, '강원도', '삼척시' );
insert into region values (seq_region_id.nextval, '강원도', '홍천군' );
insert into region values (seq_region_id.nextval, '강원도', '횡성군' );
insert into region values (seq_region_id.nextval, '강원도', '평창군' );
insert into region values (seq_region_id.nextval, '강원도', '정선군' );
insert into region values (seq_region_id.nextval, '경상남도', '창원시' );
insert into region values (seq_region_id.nextval, '경상남도', '진주시' );
insert into region values (seq_region_id.nextval, '경상남도', '통영시' );
insert into region values (seq_region_id.nextval, '경상남도', '사천시' );
insert into region values (seq_region_id.nextval, '경상남도', '김해시' );
insert into region values (seq_region_id.nextval, '경상남도', '밀양시' );
insert into region values (seq_region_id.nextval, '경상남도', '거제시' );
insert into region values (seq_region_id.nextval, '경상남도', '양산시' );
insert into region values (seq_region_id.nextval, '경상남도', '함안군' );
insert into region values (seq_region_id.nextval, '경상남도', '창녕군' );
insert into region values (seq_region_id.nextval, '경상북도', '포항시' );
insert into region values (seq_region_id.nextval, '경상북도', '경주시' );
insert into region values (seq_region_id.nextval, '경상북도', '김천시' );
insert into region values (seq_region_id.nextval, '경상북도', '안동시' );
insert into region values (seq_region_id.nextval, '경상북도', '구미시' );
insert into region values (seq_region_id.nextval, '경상북도', '영주시' );
insert into region values (seq_region_id.nextval, '경상북도', '영천시' );
insert into region values (seq_region_id.nextval, '경상북도', '상주시' );
insert into region values (seq_region_id.nextval, '경상북도', '문경시' );
insert into region values (seq_region_id.nextval, '경상북도', '경산시' );
insert into region values (seq_region_id.nextval, '대전', '대덕구' );
insert into region values (seq_region_id.nextval, '대전', '동구' );
insert into region values (seq_region_id.nextval, '대전', '서구' );
insert into region values (seq_region_id.nextval, '대전', '유성구' );
insert into region values (seq_region_id.nextval, '대전', '중구' );
insert into region values (seq_region_id.nextval, '대구', '남구' );
insert into region values (seq_region_id.nextval, '대구', '달서구' );
insert into region values (seq_region_id.nextval, '대구', '동구' );
insert into region values (seq_region_id.nextval, '대구', '북구' );
insert into region values (seq_region_id.nextval, '대구', '서구' );
insert into region values (seq_region_id.nextval, '대구', '수성구' );
insert into region values (seq_region_id.nextval, '대구', '중구' );
insert into region values (seq_region_id.nextval, '대구', '달성군' );
insert into region values (seq_region_id.nextval, '부산', '강서구' );
insert into region values (seq_region_id.nextval, '부산', '금정구' );
insert into region values (seq_region_id.nextval, '부산', '남구' );
insert into region values (seq_region_id.nextval, '부산', '동구' );
insert into region values (seq_region_id.nextval, '부산', '동래구' );
insert into region values (seq_region_id.nextval, '부산', '부산진구' );
insert into region values (seq_region_id.nextval, '부산', '북구' );
insert into region values (seq_region_id.nextval, '부산', '서구' );
insert into region values (seq_region_id.nextval, '부산', '중구' );
insert into region values (seq_region_id.nextval, '부산', '해운대구' );
insert into region values (seq_region_id.nextval, '울산', '남구' );
insert into region values (seq_region_id.nextval, '울산', '동구' );
insert into region values (seq_region_id.nextval, '울산', '북구' );
insert into region values (seq_region_id.nextval, '울산', '중구' );
insert into region values (seq_region_id.nextval, '울산', '울주군' );
insert into region values (seq_region_id.nextval, '광주', '광산구' );
insert into region values (seq_region_id.nextval, '광주', '남구' );
insert into region values (seq_region_id.nextval, '광주', '동구' );
insert into region values (seq_region_id.nextval, '광주', '북구' );
insert into region values (seq_region_id.nextval, '광주', '서구' );
insert into region values (seq_region_id.nextval, '충청남도', '홍성군' );
insert into region values (seq_region_id.nextval, '충청남도', '공주시' );
insert into region values (seq_region_id.nextval, '충청남도', '논산시' );
insert into region values (seq_region_id.nextval, '충청남도', '당진시' );
insert into region values (seq_region_id.nextval, '충청남도', '보령시' );
insert into region values (seq_region_id.nextval, '충청남도', '서산시' );
insert into region values (seq_region_id.nextval, '충청남도', '아산시' );
insert into region values (seq_region_id.nextval, '충청남도', '천안시' );
insert into region values (seq_region_id.nextval, '충청남도', '태안군' );
insert into region values (seq_region_id.nextval, '충청남도', '부여군' );
insert into region values (seq_region_id.nextval, '충청북도', '제천시' );
insert into region values (seq_region_id.nextval, '충청북도', '청주시' );
insert into region values (seq_region_id.nextval, '충청북도', '충주시' );
insert into region values (seq_region_id.nextval, '충청북도', '괴산군' );
insert into region values (seq_region_id.nextval, '충청북도', '단양군' );
insert into region values (seq_region_id.nextval, '충청북도', '보은군' );
insert into region values (seq_region_id.nextval, '충청북도', '증평군' );
insert into region values (seq_region_id.nextval, '충청북도', '진천군' );
insert into region values (seq_region_id.nextval, '충청북도', '옥천군' );
insert into region values (seq_region_id.nextval, '충청북도', '영동군' );
insert into region values (seq_region_id.nextval, '전라북도', '군산시' );
insert into region values (seq_region_id.nextval, '전라북도', '김제시' );
insert into region values (seq_region_id.nextval, '전라북도', '남원시' );
insert into region values (seq_region_id.nextval, '전라북도', '익산시' );
insert into region values (seq_region_id.nextval, '전라북도', '전주시' );
insert into region values (seq_region_id.nextval, '전라북도', '정읍시' );
insert into region values (seq_region_id.nextval, '전라북도', '고창군' );
insert into region values (seq_region_id.nextval, '전라북도', '무주군' );
insert into region values (seq_region_id.nextval, '전라북도', '순창군' );
insert into region values (seq_region_id.nextval, '전라북도', '부안군' );
insert into region values (seq_region_id.nextval, '전라남도', '광양시' );
insert into region values (seq_region_id.nextval, '전라남도', '나주시' );
insert into region values (seq_region_id.nextval, '전라남도', '목포시' );
insert into region values (seq_region_id.nextval, '전라남도', '순천시' );
insert into region values (seq_region_id.nextval, '전라남도', '여수시' );
insert into region values (seq_region_id.nextval, '전라남도', '곡성군' );
insert into region values (seq_region_id.nextval, '전라남도', '고흥군' );
insert into region values (seq_region_id.nextval, '전라남도', '완도군' );
insert into region values (seq_region_id.nextval, '전라남도', '진도군' );
insert into region values (seq_region_id.nextval, '전라남도', '함평군' );
insert into region values (seq_region_id.nextval, '제주도', '제주시' );
insert into region values (seq_region_id.nextval, '제주도', '서귀포시' );
insert into region values (seq_region_id.nextval, '세종', '조치원읍' );
insert into region values (seq_region_id.nextval, '세종', '연기면' );
insert into region values (seq_region_id.nextval, '세종', '연동면' );
insert into region values (seq_region_id.nextval, '세종', '부강면' );
insert into region values (seq_region_id.nextval, '세종', '금남면' );
insert into region values (seq_region_id.nextval, '세종', '장군면' );
insert into region values (seq_region_id.nextval, '세종', '연서면' );
insert into region values (seq_region_id.nextval, '세종', '전의면' );
insert into region values (seq_region_id.nextval, '세종', '전동면' );
insert into region values (seq_region_id.nextval, '세종', '한솔동' );


commit;

--- 멤버 

